<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlacementSeeder extends Seeder
{
    public function run()
    {
        $data = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Bekasi',
    'description' => '',
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'Bandung',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'name' => 'Yogya',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'name' => 'Jakarta',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'name' => 'Ambon',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'name' => 'BIT Office',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'name' => 'Badung',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'name' => 'Balikpapan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  8 => 
  array (
    'id' => 9,
    'name' => 'Banda Aceh',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  9 => 
  array (
    'id' => 10,
    'name' => 'Bandar Lampung',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  10 => 
  array (
    'id' => 11,
    'name' => 'Banjarmasin',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  11 => 
  array (
    'id' => 12,
    'name' => 'Banyuwangi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  12 => 
  array (
    'id' => 13,
    'name' => 'Barabai',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  13 => 
  array (
    'id' => 14,
    'name' => 'Batam',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  14 => 
  array (
    'id' => 15,
    'name' => 'Bengkulu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  15 => 
  array (
    'id' => 16,
    'name' => 'Bima',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  16 => 
  array (
    'id' => 17,
    'name' => 'Blitar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  17 => 
  array (
    'id' => 18,
    'name' => 'Bogor',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  18 => 
  array (
    'id' => 19,
    'name' => 'Bukittinggi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  19 => 
  array (
    'id' => 20,
    'name' => 'Buleleng',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  20 => 
  array (
    'id' => 21,
    'name' => 'Cianjur',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  21 => 
  array (
    'id' => 22,
    'name' => 'Cilacap',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  22 => 
  array (
    'id' => 23,
    'name' => 'Cirebon',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  23 => 
  array (
    'id' => 24,
    'name' => 'Denpasar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  24 => 
  array (
    'id' => 25,
    'name' => 'Depok',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  25 => 
  array (
    'id' => 26,
    'name' => 'Ende',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  26 => 
  array (
    'id' => 27,
    'name' => 'Gianyar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  27 => 
  array (
    'id' => 28,
    'name' => 'Gorontalo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  28 => 
  array (
    'id' => 29,
    'name' => 'Head Office Bekasi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  29 => 
  array (
    'id' => 30,
    'name' => 'Jak Pus - Jak Ut - Jak Bar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  30 => 
  array (
    'id' => 31,
    'name' => 'Jak Pus-Ut-Bar & Tgr - Banten',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  31 => 
  array (
    'id' => 32,
    'name' => 'Jak Tim-Bek & Jak Sel- Bogor',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  32 => 
  array (
    'id' => 33,
    'name' => 'Jakarta Barat',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  33 => 
  array (
    'id' => 34,
    'name' => 'Jakarta Pusat',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  34 => 
  array (
    'id' => 35,
    'name' => 'Jakarta Selatan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  35 => 
  array (
    'id' => 36,
    'name' => 'Jakarta Timur-Bekasi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  36 => 
  array (
    'id' => 37,
    'name' => 'Jambi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  37 => 
  array (
    'id' => 38,
    'name' => 'Jayapura',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  38 => 
  array (
    'id' => 39,
    'name' => 'Jember',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  39 => 
  array (
    'id' => 40,
    'name' => 'Karawang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  40 => 
  array (
    'id' => 41,
    'name' => 'Kediri',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  41 => 
  array (
    'id' => 42,
    'name' => 'Kendari',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  42 => 
  array (
    'id' => 43,
    'name' => 'Kerinci',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  43 => 
  array (
    'id' => 44,
    'name' => 'Ketapang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  44 => 
  array (
    'id' => 45,
    'name' => 'Klaten',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  45 => 
  array (
    'id' => 46,
    'name' => 'Kotawaringin Barat',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  46 => 
  array (
    'id' => 47,
    'name' => 'Kotawaringin Timur',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  47 => 
  array (
    'id' => 48,
    'name' => 'Kudus',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  48 => 
  array (
    'id' => 49,
    'name' => 'Kupang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  49 => 
  array (
    'id' => 50,
    'name' => 'Lamongan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  50 => 
  array (
    'id' => 51,
    'name' => 'Lhokseumawe',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  51 => 
  array (
    'id' => 52,
    'name' => 'Lombok Timur',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  52 => 
  array (
    'id' => 53,
    'name' => 'Lumajang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  53 => 
  array (
    'id' => 54,
    'name' => 'MIB Office',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  54 => 
  array (
    'id' => 55,
    'name' => 'Madiun',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  55 => 
  array (
    'id' => 56,
    'name' => 'Makasar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  56 => 
  array (
    'id' => 57,
    'name' => 'Malang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  57 => 
  array (
    'id' => 58,
    'name' => 'Manado',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  58 => 
  array (
    'id' => 59,
    'name' => 'Manokwari',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  59 => 
  array (
    'id' => 60,
    'name' => 'Mataram',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  60 => 
  array (
    'id' => 61,
    'name' => 'Medan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  61 => 
  array (
    'id' => 62,
    'name' => 'Merauke',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  62 => 
  array (
    'id' => 63,
    'name' => 'Musi Banyuasin',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  63 => 
  array (
    'id' => 64,
    'name' => 'Ogan Komering Ilir',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  64 => 
  array (
    'id' => 65,
    'name' => 'Ogan Komering Ulu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  65 => 
  array (
    'id' => 66,
    'name' => 'Padang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  66 => 
  array (
    'id' => 67,
    'name' => 'Padang Sidempuan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  67 => 
  array (
    'id' => 68,
    'name' => 'Palangkaraya',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  68 => 
  array (
    'id' => 69,
    'name' => 'Palembang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  69 => 
  array (
    'id' => 70,
    'name' => 'Palopo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  70 => 
  array (
    'id' => 71,
    'name' => 'Palu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  71 => 
  array (
    'id' => 72,
    'name' => 'Pangkal Pinang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  72 => 
  array (
    'id' => 73,
    'name' => 'Pare Pare',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  73 => 
  array (
    'id' => 74,
    'name' => 'Paser',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  74 => 
  array (
    'id' => 75,
    'name' => 'Pekalongan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  75 => 
  array (
    'id' => 76,
    'name' => 'Pekanbaru',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  76 => 
  array (
    'id' => 77,
    'name' => 'Pematang Siantar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  77 => 
  array (
    'id' => 78,
    'name' => 'Pontianak',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  78 => 
  array (
    'id' => 79,
    'name' => 'Probolinggo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  79 => 
  array (
    'id' => 80,
    'name' => 'Purwakarta',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  80 => 
  array (
    'id' => 81,
    'name' => 'Purwokerto',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  81 => 
  array (
    'id' => 82,
    'name' => 'Samarinda',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  82 => 
  array (
    'id' => 83,
    'name' => 'Semarang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  83 => 
  array (
    'id' => 84,
    'name' => 'Serang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  84 => 
  array (
    'id' => 85,
    'name' => 'Sidoarjo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  85 => 
  array (
    'id' => 86,
    'name' => 'Singkawang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  86 => 
  array (
    'id' => 87,
    'name' => 'Sintang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  87 => 
  array (
    'id' => 88,
    'name' => 'Solo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  88 => 
  array (
    'id' => 89,
    'name' => 'Sorong',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  89 => 
  array (
    'id' => 90,
    'name' => 'Sukabumi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  90 => 
  array (
    'id' => 91,
    'name' => 'Surabaya',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  91 => 
  array (
    'id' => 92,
    'name' => 'Surakarta',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  92 => 
  array (
    'id' => 93,
    'name' => 'Tabanan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  93 => 
  array (
    'id' => 94,
    'name' => 'Tanah Bumbu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  94 => 
  array (
    'id' => 95,
    'name' => 'Tangerang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  95 => 
  array (
    'id' => 96,
    'name' => 'Tanjung Pinang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  96 => 
  array (
    'id' => 97,
    'name' => 'Tarakan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  97 => 
  array (
    'id' => 98,
    'name' => 'Tasikmalaya',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  98 => 
  array (
    'id' => 99,
    'name' => 'Tegal',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  99 => 
  array (
    'id' => 100,
    'name' => 'Ternate',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  100 => 
  array (
    'id' => 101,
    'name' => 'Timika',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  101 => 
  array (
    'id' => 102,
    'name' => 'Warehouse Mampang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  102 => 
  array (
    'id' => 103,
    'name' => 'Way Kanan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  103 => 
  array (
    'id' => 104,
    'name' => 'Yogyakarta',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  104 => 
  array (
    'id' => 105,
    'name' => 'Aceh Besar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  105 => 
  array (
    'id' => 106,
    'name' => 'Langsa',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  106 => 
  array (
    'id' => 107,
    'name' => 'Meulaboh',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  107 => 
  array (
    'id' => 108,
    'name' => 'Sabang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  108 => 
  array (
    'id' => 109,
    'name' => 'Subulussalam',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  109 => 
  array (
    'id' => 110,
    'name' => 'Binjai',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  110 => 
  array (
    'id' => 111,
    'name' => 'Gunungsitoli',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  111 => 
  array (
    'id' => 112,
    'name' => 'Padangsidimpuan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  112 => 
  array (
    'id' => 113,
    'name' => 'Pematangsiantar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  113 => 
  array (
    'id' => 114,
    'name' => 'Sibolga',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  114 => 
  array (
    'id' => 115,
    'name' => 'Tanjungbalai',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  115 => 
  array (
    'id' => 116,
    'name' => 'Tebing Tinggi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  116 => 
  array (
    'id' => 117,
    'name' => 'Padangpanjang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  117 => 
  array (
    'id' => 118,
    'name' => 'Pariaman',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  118 => 
  array (
    'id' => 119,
    'name' => 'Payakumbuh',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  119 => 
  array (
    'id' => 120,
    'name' => 'Sawahlunto',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  120 => 
  array (
    'id' => 121,
    'name' => 'Solok',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  121 => 
  array (
    'id' => 122,
    'name' => 'Dumai',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  122 => 
  array (
    'id' => 123,
    'name' => 'Tanjungpinang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  123 => 
  array (
    'id' => 124,
    'name' => 'Sungai Penuh',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  124 => 
  array (
    'id' => 125,
    'name' => 'Lubuklinggau',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  125 => 
  array (
    'id' => 126,
    'name' => 'Pagar Alam',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  126 => 
  array (
    'id' => 127,
    'name' => 'Prabumulih',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  127 => 
  array (
    'id' => 128,
    'name' => 'Metro',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  128 => 
  array (
    'id' => 129,
    'name' => 'Banjar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  129 => 
  array (
    'id' => 130,
    'name' => 'Cimahi',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  130 => 
  array (
    'id' => 131,
    'name' => 'Magelang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  131 => 
  array (
    'id' => 132,
    'name' => 'Salatiga',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  132 => 
  array (
    'id' => 133,
    'name' => 'Batu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  133 => 
  array (
    'id' => 134,
    'name' => 'Mojokerto',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  134 => 
  array (
    'id' => 135,
    'name' => 'Pasuruan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  135 => 
  array (
    'id' => 136,
    'name' => 'Cilegon',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  136 => 
  array (
    'id' => 137,
    'name' => 'Tangerang Selatan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  137 => 
  array (
    'id' => 138,
    'name' => 'Palangka Raya',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  138 => 
  array (
    'id' => 139,
    'name' => 'Banjarbaru',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  139 => 
  array (
    'id' => 140,
    'name' => 'Bontang',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  140 => 
  array (
    'id' => 141,
    'name' => 'Bitung',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  141 => 
  array (
    'id' => 142,
    'name' => 'Kotamobagu',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  142 => 
  array (
    'id' => 143,
    'name' => 'Tomohon',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  143 => 
  array (
    'id' => 144,
    'name' => 'Makassar',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  144 => 
  array (
    'id' => 145,
    'name' => 'Parepare',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  145 => 
  array (
    'id' => 146,
    'name' => 'Bau-Bau',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  146 => 
  array (
    'id' => 147,
    'name' => 'Mamuju',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  147 => 
  array (
    'id' => 148,
    'name' => 'Tual',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  148 => 
  array (
    'id' => 149,
    'name' => 'Tidore Kepulauan',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  149 => 
  array (
    'id' => 150,
    'name' => 'Labuan Bajo',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  150 => 
  array (
    'id' => 151,
    'name' => 'Pangkalanbun',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  151 => 
  array (
    'id' => 152,
    'name' => 'Sampit',
    'description' => NULL,
    'created_by' => NULL,
    'updated_by' => NULL,
    'deleted_by' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
);

        foreach (array_chunk($data, 100) as $chunk) {
            foreach ($chunk as $item) {
                DB::table('iq_placement')->updateOrInsert(['id' => $item['id']], $item);
            }
        }
    }
}
