<?php

namespace Database\Seeders\Appraisals;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AppraisalQuestionSeeder extends Seeder
{
    public function run()
    {
        $now = '2026-09-15 11:40:00';
        $createdBy = '7df26957-6614-4c96-bde0-340ead4504ee';

        $data = [
            // =========================================================================
            // TEMPLATE 1: Template HR - PT Dieboldnixdorf (Manager / HR - 3 Cat x 3 Questions)
            // =========================================================================
            // Category 1: Technical Ability & Work Result (Total Weight: 40%)
            [
                'id' => 1,
                'template_id' => 1,
                'category_id' => 1,
                'group_kpi' => 'Pencapaian Target Departemen',
                'question' => 'Pencapaian Key Performance Indicators (KPI) unit kerja sesuai target tahunan',
                'formula_description' => "Tercapai 100% = 10\nTercapai 90-99% = 8\nTercapai 80-89% = 6\nTercapai <80% = 4",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'template_id' => 1,
                'category_id' => 1,
                'group_kpi' => 'Efisiensi Operasional & Budget',
                'question' => 'Pengelolaan penggunaan anggaran dan efisiensi proses bisnis unit kerja',
                'formula_description' => "Sesuai budget = 10\nOver budget <5% = 8\nOver budget 5-10% = 6\nOver budget >10% = 4",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'template_id' => 1,
                'category_id' => 1,
                'group_kpi' => 'Inovasi & Pengembangan Proses',
                'question' => 'Kemampuan menginisiasi perbaikan berkelanjutan dan efisiensi kerja di departemen',
                'formula_description' => "Inovatif & implementatif = 10\nPerbaikan rutin = 8\nCukup = 6\nKurang inisiatif = 4",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 2: Behavior & Work Processes (Total Weight: 40%)
            [
                'id' => 4,
                'template_id' => 1,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Communication)',
                'question' => "Kemampuan untuk berkomunikasi dua arah secara efektif dan mendengarkan responsif",
                'formula_description' => "1-3 = Pasif\n4-6 = Mampu merespon\n7-8 = Mendengar responsif\n9-10 = Sangat komunikatif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'template_id' => 1,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Customer Service Orientation)',
                'question' => 'Kemampuan untuk membantu dan melayani customer internal maupun eksternal',
                'formula_description' => "1-3 = Respon seadanya\n4-6 = Menindaklanjuti keluhan\n7-8 = Memperbaiki masalah\n9-10 = Memberikan solusi proaktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'template_id' => 1,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Integrity & Teamwork)',
                'question' => 'Menunjukkan komitmen tinggi, kejujuran, dan kemampuan bekerja sama lintas unit',
                'formula_description' => "1-3 = Pasif\n4-6 = Kooperatif\n7-8 = Memberikan semangat\n9-10 = Menjadi teladan integritas & tim",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 3: Leadership (Total Weight: 20%)
            [
                'id' => 7,
                'template_id' => 1,
                'category_id' => 3,
                'group_kpi' => 'Leadership (Strategic Thinking)',
                'question' => 'Kemampuan menyusun dan mengeksekusi strategi unit kerja sesuai visi misi perusahaan',
                'formula_description' => "1-3 = Memahami strategi dasar\n4-6 = Mengimplementasi rencana kerja\n7-8 = Mengoptimalkan strategi unit\n9-10 = Merumuskan strategi inovatif",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'template_id' => 1,
                'category_id' => 3,
                'group_kpi' => 'Leadership (People Development)',
                'question' => 'Kemampuan membimbing, mengarahkan, dan mengembangkan kompetensi anggota tim',
                'formula_description' => "1-3 = Memberi arahan umum\n4-6 = Melakukan coaching rutin\n7-8 = Mengembangkan kompetensi tim\n9-10 = Menciptakan kader pemimpin baru",
                'weight' => 5,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'template_id' => 1,
                'category_id' => 3,
                'group_kpi' => 'Leadership (Decision Making)',
                'question' => 'Kemampuan mengambil keputusan yang tepat, cepat, dan bertanggung jawab terhadap risiko',
                'formula_description' => "1-3 = Ragu-ragu\n4-6 = Keputusan standar\n7-8 = Tepat & terukur\n9-10 = Visioner & solutif",
                'weight' => 5,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================================================================
            // TEMPLATE 2: Template Staff - PT Dieboldnixdorf (STAFF -> 2 Cat x 3 Questions, NO LEADERSHIP)
            // =========================================================================
            // Category 1: Technical Ability & Work Result (Total Weight: 60%)
            [
                'id' => 10,
                'template_id' => 2,
                'category_id' => 1,
                'group_kpi' => 'Kualitas Hasil Pekerjaan',
                'question' => 'Hasil penyelesaian tugas sesuai dengan petunjuk teknis dan bebas dari kesalahan',
                'formula_description' => "Bebas error = 10\nError <2% = 8\nError 2-5% = 6\nError >5% = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'template_id' => 2,
                'category_id' => 1,
                'group_kpi' => 'Ketepatan Waktu (Punctuality)',
                'question' => 'Penyelesaian tugas harian/mingguan sesuai deadline yang telah ditentukan',
                'formula_description' => "On time 100% = 10\nTerlambat 1 kali = 8\nTerlambat 2 kali = 6\nTerlambat >2 kali = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'template_id' => 2,
                'category_id' => 1,
                'group_kpi' => 'Kepatuhan Prosedur Kerja (SOP)',
                'question' => 'Kepatuhan terhadap standar operasional prosedur dan instruksi kerja operasional',
                'formula_description' => "Sesuai SOP 100% = 10\nMinor deviation = 8\nModerate deviation = 6\nMajor deviation = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 2: Behavior & Work Processes (Total Weight: 40%)
            [
                'id' => 13,
                'template_id' => 2,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Communication)',
                'question' => "Kemampuan untuk berkomunikasi dua arah secara jelas dan responsif dalam tim",
                'formula_description' => "1-3 = Pasif\n4-6 = Mampu merespon\n7-8 = Mendengar responsif\n9-10 = Komunikatif & aktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'template_id' => 2,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Customer Service Orientation)',
                'question' => 'Kemampuan membantu dan melayani rekan kerja serta customer dengan ramah dan solutif',
                'formula_description' => "1-3 = Respon seadanya\n4-6 = Menindaklanjuti kebutuhan\n7-8 = Melayani dengan baik\n9-10 = Pelayanan prima & proaktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'template_id' => 2,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Integrity & Teamwork)',
                'question' => 'Menunjukkan kejujuran, disiplin kerja, serta kesediaan membantu anggota tim lain',
                'formula_description' => "1-3 = Pasif\n4-6 = Kooperatif\n7-8 = Solid & disiplin\n9-10 = Teladan kerja sama",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================================================================
            // TEMPLATE 3: Template HR - PT Hitachi (Manager / HR - 3 Cat x 3 Questions)
            // =========================================================================
            // Category 1: Technical Ability & Work Result (Total Weight: 40%)
            [
                'id' => 16,
                'template_id' => 3,
                'category_id' => 1,
                'group_kpi' => 'Pencapaian Target Departemen',
                'question' => 'Pencapaian Key Performance Indicators (KPI) unit kerja sesuai target tahunan',
                'formula_description' => "Tercapai 100% = 10\nTercapai 90-99% = 8\nTercapai 80-89% = 6\nTercapai <80% = 4",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'template_id' => 3,
                'category_id' => 1,
                'group_kpi' => 'Efisiensi Operasional & Budget',
                'question' => 'Pengelolaan penggunaan anggaran dan efisiensi proses bisnis unit kerja',
                'formula_description' => "Sesuai budget = 10\nOver budget <5% = 8\nOver budget 5-10% = 6\nOver budget >10% = 4",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'template_id' => 3,
                'category_id' => 1,
                'group_kpi' => 'Inovasi & Pengembangan Proses',
                'question' => 'Kemampuan menginisiasi perbaikan berkelanjutan dan efisiensi kerja di departemen',
                'formula_description' => "Inovatif & implementatif = 10\nPerbaikan rutin = 8\nCukup = 6\nKurang inisiatif = 4",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 2: Behavior & Work Processes (Total Weight: 40%)
            [
                'id' => 19,
                'template_id' => 3,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Communication)',
                'question' => "Kemampuan untuk berkomunikasi dua arah secara efektif dan mendengarkan responsif",
                'formula_description' => "1-3 = Pasif\n4-6 = Mampu merespon\n7-8 = Mendengar responsif\n9-10 = Sangat komunikatif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'template_id' => 3,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Customer Service Orientation)',
                'question' => 'Kemampuan untuk membantu dan melayani customer internal maupun eksternal',
                'formula_description' => "1-3 = Respon seadanya\n4-6 = Menindaklanjuti keluhan\n7-8 = Memperbaiki masalah\n9-10 = Memberikan solusi proaktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'template_id' => 3,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Integrity & Teamwork)',
                'question' => 'Menunjukkan komitmen tinggi, kejujuran, dan kemampuan bekerja sama lintas unit',
                'formula_description' => "1-3 = Pasif\n4-6 = Kooperatif\n7-8 = Memberikan semangat\n9-10 = Menjadi teladan integritas & tim",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 3: Leadership (Total Weight: 20%)
            [
                'id' => 22,
                'template_id' => 3,
                'category_id' => 3,
                'group_kpi' => 'Leadership (Strategic Thinking)',
                'question' => 'Kemampuan menyusun dan mengeksekusi strategi unit kerja sesuai visi misi perusahaan',
                'formula_description' => "1-3 = Memahami strategi dasar\n4-6 = Mengimplementasi rencana kerja\n7-8 = Mengoptimalkan strategi unit\n9-10 = Merumuskan strategi inovatif",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'template_id' => 3,
                'category_id' => 3,
                'group_kpi' => 'Leadership (People Development)',
                'question' => 'Kemampuan membimbing, mengarahkan, dan mengembangkan kompetensi anggota tim',
                'formula_description' => "1-3 = Memberi arahan umum\n4-6 = Melakukan coaching rutin\n7-8 = Mengembangkan kompetensi tim\n9-10 = Menciptakan kader pemimpin baru",
                'weight' => 5,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'template_id' => 3,
                'category_id' => 3,
                'group_kpi' => 'Leadership (Decision Making)',
                'question' => 'Kemampuan mengambil keputusan yang tepat, cepat, dan bertanggung jawab terhadap risiko',
                'formula_description' => "1-3 = Ragu-ragu\n4-6 = Keputusan standar\n7-8 = Tepat & terukur\n9-10 = Visioner & solutif",
                'weight' => 5,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================================================================
            // TEMPLATE 4: Template Staff - PT Hitachi (STAFF -> 2 Cat x 3 Questions, NO LEADERSHIP)
            // =========================================================================
            // Category 1: Technical Ability & Work Result (Total Weight: 60%)
            [
                'id' => 25,
                'template_id' => 4,
                'category_id' => 1,
                'group_kpi' => 'Kualitas Hasil Pekerjaan',
                'question' => 'Hasil penyelesaian tugas sesuai dengan petunjuk teknis dan bebas dari kesalahan',
                'formula_description' => "Bebas error = 10\nError <2% = 8\nError 2-5% = 6\nError >5% = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'template_id' => 4,
                'category_id' => 1,
                'group_kpi' => 'Ketepatan Waktu (Punctuality)',
                'question' => 'Penyelesaian tugas harian/mingguan sesuai deadline yang telah ditentukan',
                'formula_description' => "On time 100% = 10\nTerlambat 1 kali = 8\nTerlambat 2 kali = 6\nTerlambat >2 kali = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'template_id' => 4,
                'category_id' => 1,
                'group_kpi' => 'Kepatuhan Prosedur Kerja (SOP)',
                'question' => 'Kepatuhan terhadap standar operasional prosedur dan instruksi kerja operasional',
                'formula_description' => "Sesuai SOP 100% = 10\nMinor deviation = 8\nModerate deviation = 6\nMajor deviation = 4",
                'weight' => 20,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Category 2: Behavior & Work Processes (Total Weight: 40%)
            [
                'id' => 28,
                'template_id' => 4,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Communication)',
                'question' => "Kemampuan untuk berkomunikasi dua arah secara jelas dan responsif dalam tim",
                'formula_description' => "1-3 = Pasif\n4-6 = Mampu merespon\n7-8 = Mendengar responsif\n9-10 = Komunikatif & aktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'template_id' => 4,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Customer Service Orientation)',
                'question' => 'Kemampuan membantu dan melayani rekan kerja serta customer dengan ramah dan solutif',
                'formula_description' => "1-3 = Respon seadanya\n4-6 = Menindaklanjuti kebutuhan\n7-8 = Melayani dengan baik\n9-10 = Pelayanan prima & proaktif",
                'weight' => 15,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'template_id' => 4,
                'category_id' => 2,
                'group_kpi' => 'Core Competency (Integrity & Teamwork)',
                'question' => 'Menunjukkan kejujuran, disiplin kerja, serta kesediaan membantu anggota tim lain',
                'formula_description' => "1-3 = Pasif\n4-6 = Kooperatif\n7-8 = Solid & disiplin\n9-10 = Teladan kerja sama",
                'weight' => 10,
                'created_by' => $createdBy,
                'updated_by' => $createdBy,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $allowedIds = array_column($data, 'id');
        DB::table('iq_appraisal_question')->whereNotIn('id', $allowedIds)->delete();

        foreach ($data as $item) {
            DB::table('iq_appraisal_question')->updateOrInsert(['id' => $item['id']], $item);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
