[program:laravel-echo]
process_name=%(program_name)s_%(process_num)02d
command=/var/www/laravel-echo-server start
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-echo.log
